Added config and some plugin code to Common project. Many minor changes made while SVN was not available.
git-svn-id: https://svn.pedal.me.uk/repos/combined/trunk@132 378dcfd6-f8a6-c149-9150-5c8ef5bc3a15

diff --git a/package-project b/package-project
--- a/package-project
+++ b/package-project
@@ -34,11 +34,9 @@ fi
 
 if ! [ -d "$source_folder" ]
 then
-	echo "source folder $source_folder does not exist or is not a folder" >&2
+	echo "Error: source folder $source_folder does not exist or is not a folder" >&2
 	exit 1
 fi
-
-
 
 mkdir "$package_folder"
 
